name: vtfriend
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  bubble: ^1.2.1
  chat_bubbles: ^1.6.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  google_generative_ai: ^0.4.0
  hexcolor: ^3.0.1
  path: ^1.9.0
  sqflite: ^2.3.3+1
  web_socket_channel: ^2.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/icon/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk
flutter:
  uses-material-design: true
